name: CI

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  deployment:
    name: setup
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: pongo install
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        git clone https://github.com/Kong/kong-pongo.git
        mkdir -p ~/.local/bin
        ln -s $(realpath kong-pongo/pongo.sh) ~/.local/bin/pongo
    - name: publish
      run: |
        ./run.sh
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
